package com.polydes.repman.util.maven;

import java.io.InputStream;
import java.net.HttpURLConnection;
import java.net.URI;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.util.HashMap;
import java.util.Map;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;

/*
 * Generated by Gemini
 */
public class EnforcedPlatformBomResolver {

    /**
     * Downloads a BOM from a Maven repository and maps GroupID:ArtifactID to its Version.
     */
    public static Map<String, String> resolvePlatformVersions(
            Path cacheRoot, String repoUrl, String groupId, String artifactId, String version) throws Exception {

        // 1. Construct the Maven repository URL for the POM file
        String groupPath = groupId.replace('.', '/');

        Path localPomPath = cacheRoot.resolve(groupPath)
                .resolve(artifactId)
                .resolve(version)
                .resolve(artifactId + "-" + version + ".pom");
        if (Files.exists(localPomPath)) {
            System.out.println("Cache HIT: Reading BOM from " + localPomPath);
        } else {
            String baseUrl = repoUrl.endsWith("/") ? repoUrl : repoUrl + "/";
            String pomUrl = String.format("%s%s/%s/%s/%s-%s.pom", baseUrl, groupPath, artifactId, version, artifactId, version);

            System.out.println("Fetching BOM from: " + pomUrl);

            // 2. Fetch the POM XML
            HttpURLConnection connection = (HttpURLConnection) URI.create(pomUrl).toURL().openConnection();
            connection.setRequestMethod("GET");
            connection.setRequestProperty("Accept", "application/xml");

            if (connection.getResponseCode() != 200) {
                throw new RuntimeException("Failed to download BOM. HTTP Code: " + connection.getResponseCode());
            }

            Files.createDirectories(localPomPath.getParent());

            try (InputStream is = connection.getInputStream()) {
                Files.copy(is, localPomPath, StandardCopyOption.REPLACE_EXISTING);
            }
            System.out.println("Saved BOM to cache: " + localPomPath);
        }

        // 3. Parse the XML Document
        DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
        // Prevent XML External Entity (XXE) injection for safety
        factory.setFeature("http://apache.org/xml/features/disallow-doctype-decl", true);
        DocumentBuilder builder = factory.newDocumentBuilder();

        Map<String, String> versionMapping = new HashMap<>();

        try (InputStream is = Files.newInputStream(localPomPath)) {
            Document doc = builder.parse(is);
            doc.getDocumentElement().normalize();

            // Extract <properties> just in case the Gradle BOM utilized them
            Map<String, String> properties = extractProperties(doc);

            // 4. Extract dependencies strictly under <dependencyManagement>
            NodeList dependencies = doc.getElementsByTagName("dependency");

            for (int i = 0; i < dependencies.getLength(); i++) {
                Element depElement = (Element) dependencies.item(i);

                // Ensure this <dependency> is actually inside <dependencyManagement>
                Node parent = depElement.getParentNode(); // <dependencies>
                Node grandParent = parent != null ? parent.getParentNode() : null; // <dependencyManagement>

                if (grandParent != null && "dependencyManagement".equals(grandParent.getNodeName())) {
                    String depGroupId = getTagValue(depElement, "groupId");
                    String depArtifactId = getTagValue(depElement, "artifactId");
                    String depVersion = getTagValue(depElement, "version");

                    if (depGroupId != null && depArtifactId != null && depVersion != null) {
                        // Resolve property placeholder if one exists (e.g. ${foo.version})
                        depVersion = resolveVersionProperty(depVersion, properties);

                        // Map "groupId:artifactId" -> "version"
                        String coordinates = depGroupId + ":" + depArtifactId;
                        versionMapping.put(coordinates, depVersion);
                    }
                }
            }
        }

        return versionMapping;
    }

    /**
     * Helper to retrieve text content from a specific XML tag.
     */
    private static String getTagValue(Element parent, String tagName) {
        NodeList list = parent.getElementsByTagName(tagName);
        if (list != null && list.getLength() > 0) {
            return list.item(0).getTextContent().trim();
        }
        return null;
    }

    /**
     * Extracts the <properties> block from the POM to resolve version variables.
     */
    private static Map<String, String> extractProperties(Document doc) {
        Map<String, String> properties = new HashMap<>();
        NodeList propNodes = doc.getElementsByTagName("properties");
        if (propNodes.getLength() > 0) {
            Element propsElement = (Element) propNodes.item(0);
            NodeList propChildren = propsElement.getChildNodes();
            for (int i = 0; i < propChildren.getLength(); i++) {
                Node node = propChildren.item(i);
                if (node.getNodeType() == Node.ELEMENT_NODE) {
                    properties.put(node.getNodeName(), node.getTextContent().trim());
                }
            }
        }
        return properties;
    }

    /**
     * Resolves variables like ${library.version} using the extracted POM properties.
     */
    private static String resolveVersionProperty(String version, Map<String, String> properties) {
        if (version.startsWith("${") && version.endsWith("}")) {
            String propertyName = version.substring(2, version.length() - 1);
            return properties.getOrDefault(propertyName, version); // Fallback to raw string if missing
        }
        return version;
    }
}