package com.polydes.repman.util;

import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.net.http.HttpHeaders;
import java.util.ArrayList;
import java.util.List;

//Generated by Gemini
public class GitHubTagFetcher {

    private static final String GITHUB_PAT = System.getProperty("github.pat");

    // 1. Share a single HttpClient.
    // It automatically manages an efficient HTTP/2 connection pool.
    private static final HttpClient HTTP_CLIENT = HttpClient.newBuilder()
            .followRedirects(HttpClient.Redirect.NORMAL)
            .build();

    public static List<String> fetchAllTags(String repoOwnerAndName) throws Exception {
        List<String> allPages = new ArrayList<>();

        // Start with the first page, requesting the maximum 100 items per page
        String nextUrl = "https://api.github.com/repos/" + repoOwnerAndName + "/tags?per_page=100";

        // 4. Synchronous-looking loop (made highly concurrent by Virtual Threads)
        while (nextUrl != null) {
            HttpRequest request = HttpRequest.newBuilder()
                    .uri(URI.create(nextUrl))
                    .header("Accept", "application/vnd.github+json")
                    .header("Authorization", "Bearer " + GITHUB_PAT)
                    .header("X-GitHub-Api-Version", "2022-11-28")
                    .GET()
                    .build();

            HttpResponse<String> response = HTTP_CLIENT.send(request, HttpResponse.BodyHandlers.ofString());

            if (response.statusCode() != 200) {
                throw new RuntimeException("Failed to fetch tags for " + repoOwnerAndName + ": " + response.body());
            }

            // Add the raw JSON string array for this specific page
            allPages.add(response.body());

            // Extract the next URL from the Link header to continue the loop
            nextUrl = extractNextLink(response.headers());
        }

        return allPages;
    }

    /**
     * Parses the standard RFC 5988 Link header looking for the rel="next" URL.
     */
    private static String extractNextLink(HttpHeaders headers) {
        return headers.firstValue("Link").map(linkHeader -> {
            // The header format looks like:
            // <https://api.github.com/...page=2>; rel="next", <https://api.github.com/...page=5>; rel="last"
            String[] parts = linkHeader.split(",");
            for (String part : parts) {
                if (part.contains("rel=\"next\"")) {
                    int start = part.indexOf('<');
                    int end = part.indexOf('>');
                    if (start >= 0 && end > start) {
                        return part.substring(start + 1, end);
                    }
                }
            }
            return null; // No "next" link means we reached the final page
        }).orElse(null);
    }
}