package com.polydes.repman.util;

import org.eclipse.jgit.api.Git;
import org.eclipse.jgit.lib.StoredConfig;
import java.io.File;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

//Generated by Gemini
public class GitRemoteParser
{
    // Matches both SSH and HTTPS GitHub URLs, optionally ending in .git
    private static final Pattern GITHUB_URL_PATTERN =
            Pattern.compile("github\\.com[:/]([^/]+)/([^/]+?)(?:\\.git)?$");

    public static String getRepoOwnerAndName(File localRepoDir) throws Exception {
        try (Git git = Git.open(localRepoDir)) {
            StoredConfig config = git.getRepository().getConfig();

            // Get all configured remotes
            Set<String> remotes = config.getSubsections("remote");
            if (remotes.isEmpty()) {
                throw new IllegalStateException("No remotes configured for this repository.");
            }

            // Since we assume only one remote, grab the first one (usually "origin")
            String remoteName = remotes.contains("origin") ? "origin" : remotes.iterator().next();
            String remoteUrl = config.getString("remote", remoteName, "url");

            return parseUrl(remoteUrl);
        }
    }

    private static String parseUrl(String url) {
        if (url == null || url.isBlank()) {
            throw new IllegalArgumentException("Remote URL is empty.");
        }

        Matcher matcher = GITHUB_URL_PATTERN.matcher(url);
        if (matcher.find()) {
            String owner = matcher.group(1);
            String repoName = matcher.group(2);
            return owner + "/" + repoName;
        }

        throw new IllegalArgumentException("Could not parse owner/name from URL: " + url);
    }
}