package com.polydes.repman.util;

import org.json.JSONArray;
import org.json.JSONObject;

import java.util.ArrayList;
import java.util.List;

//Generated by Gemini
public class TagParser {

    /**
     * Parses the raw JSON pages returned by the GitHub API into a flat list of tag names.
     */
    public static List<String> extractTagNames(List<String> jsonPages) {
        List<String> allTags = new ArrayList<>();

        for (String pageJson : jsonPages) {
            // 1. Parse the raw JSON string into a JSONArray
            JSONArray tagsArray = new JSONArray(pageJson);

            // 2. Iterate through the array
            for (int i = 0; i < tagsArray.length(); i++) {
                // 3. Get each tag object
                JSONObject tagObject = tagsArray.getJSONObject(i);

                // 4. Extract the "name" field
                String tagName = tagObject.getString("name");
                allTags.add(tagName);

                // If you also need the commit SHA, you can access the nested object:
                // String sha = tagObject.getJSONObject("commit").getString("sha");
            }
        }

        return allTags;
    }
}